/*
 * exporter.js — 导出自包含 SVG（Blob 下载 / 复制源码）
 * 兼容性处理：
 *  - 内联全部样式与渐变，无外部引用
 *  - 同时写 xmlns 与 xmlns:xlink，width/height/viewBox 齐全
 *  - 混合模式以内联 style 输出（浏览器直接打开 SVG 时可正常渲染）
 */
(function (global) {
  'use strict';

  function buildDocument(state) {
    var filter = FilterEngine.buildFilter(state.chain, 'fx');
    var esc = function (s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;'); };
    var blendStyle = state.blendMode !== 'normal' || state.opacity < 1
      ? ' style="mix-blend-mode:' + state.blendMode + ';opacity:' + state.opacity + '"' : '';
    return '<?xml version="1.0" encoding="UTF-8"?>\n' +
      '<!-- Generated by SVG Filter Lab. ' + esc(CompatDetect().browser) + ' -->\n' +
      '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" ' +
      'width="' + Scene.W + '" height="' + Scene.H + '" viewBox="0 0 ' + Scene.W + ' ' + Scene.H + '">\n' +
      '  <defs>\n    ' + Scene.defs() + '\n    ' + filter.svg + '\n  </defs>\n' +
      '  <rect width="100%" height="100%" fill="#101418"/>\n' +
      '  <g filter="url(#fx)">\n    ' + Scene.layerA() + '\n  </g>\n' +
      '  <g' + blendStyle + '>\n    ' + Scene.layerB() + '\n  </g>\n' +
      '</svg>\n';
  }

  function CompatDetect() {
    return (typeof Compat !== 'undefined') ? Compat.detect() : { browser: 'unknown' };
  }

  function download(state, filename) {
    var svg = buildDocument(state);
    var blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = filename || 'filter-lab.svg';
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(function () { URL.revokeObjectURL(url); }, 5000);
    return svg;
  }

  global.Exporter = { buildDocument: buildDocument, download: download };
})(window);
